//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2parcial
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivosFijo
    {
        public int AFijoID { get; set; }
        public string Descripcion { get; set; }
        public int DepID { get; set; }
        public int TActivoID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal Valor { get; set; }
        public decimal DepreAcumulada { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual TipoDeActivo TipoDeActivo { get; set; }
    }
}
