//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2parcial
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeActivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDeActivo()
        {
            this.ActivosFijos = new HashSet<ActivosFijo>();
        }
    
        public int TActivoID { get; set; }
        public string Descripcion { get; set; }
        public int CCCompra { get; set; }
        public int CCDepreciacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivosFijo> ActivosFijos { get; set; }
    }
}
